### ISSUE TITLE
Possible mono incompatibility?

### ISSUE THREAD

**Issue by ghost** [tomakita/Colorful.Console#37]
Been developing a project using Visual Studio 2015 using Colorful.Console.
Verified that it builds & runs using VS & Windows.
Verified that it builds using Mono 4.6 and runs on Windows.
However, trying to run either (Built on Windows or built on Mono) on Linux using mono results in an undefined entry point exception.

Here is the stack trace: https://puu.sh/wBLPg/e05ad8cf11.png

**Comment by arutkowski00** [comment]
I've noticed the same thing using mono and targetting .NET Framework 4.5. Here is the stack trace:
```c#
Unhandled Exception:
System.TypeInitializationException: The type initializer for 'Colorful.Console' threw an exception. ---> System.EntryPointNotFoundException: GetStdHandle
  at (wrapper managed-to-native) Colorful.ColorMapper:GetStdHandle (int)
  at Colorful.ColorMapper.GetBufferColors () [0x00007] in <3523064a174f47afbb659c0d730fe85b>:0 
  at Colorful.Console..cctor () [0x00178] in <3523064a174f47afbb659c0d730fe85b>:0 
   --- End of inner exception stack trace ---
```

```
$ mono --version
Mono JIT compiler version 5.0.0 (Stable 5.0.0.100/9667aa6 Wed Jul 12 17:00:30 UTC 2017)
```

**Comment by oliverlukedavenport** [comment]
I'm also getting the exact same exception thrown on Ubuntu.

```
$ mono --version
Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
```

**Comment by tomakita** [comment]
Thanks for reporting this issue!  May I ask what version of Colorful.Console you're all using?  I would expect this to have been fixed as of version 1.0.7, but that may not be the case.

**Comment by tomakita** [comment]
Upon further investigation, I believe this was a bug that existed past 1.0.7, but should be fixed as of version 1.2.1.  Let me know what happens if you try that version!

**Comment by rumschuettel** [comment]
It still exists;
`$ mono --version
Mono JIT compiler version 5.4.1.6 (tarball Wed Nov  8 20:35:02 UTC 2017)`

compiles fine with target mono/.net 4.5, but throws the following exception:
```Unhandled Exception:
System.TypeInitializationException: The type initializer for 'Colorful.Console' threw an exception. ---> System.EntryPointNotFoundException: GetStdHandle
  at (wrapper managed-to-native) Colorful.ColorMapper:GetStdHandle (int)
  at Colorful.ColorMapper.GetBufferColors () [0x00007] in <8bd381b5fce54663ae8ff03962192106>:0 
  at Colorful.Console..cctor () [0x00184] in <8bd381b5fce54663ae8ff03962192106>:0 
   --- End of inner exception stack trace ---
  at LearnApp.main (System.String[] _arg1) [0x0001e] in <5a0da8faf1be3d05a7450383faa80d5a>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'Colorful.Console' threw an exception. ---> System.EntryPointNotFoundException: GetStdHandle
  at (wrapper managed-to-native) Colorful.ColorMapper:GetStdHandle (int)
  at Colorful.ColorMapper.GetBufferColors () [0x00007] in <8bd381b5fce54663ae8ff03962192106>:0 
  at Colorful.Console..cctor () [0x00184] in <8bd381b5fce54663ae8ff03962192106>:0 
   --- End of inner exception stack trace ---
  at LearnApp.main (System.String[] _arg1) [0x0001e] in <5a0da8faf1be3d05a7450383faa80d5a>:0```

**Comment by deviousasti** [comment]
This still exists in Mono 6, in Ubuntu and Debian.

**Comment by z3nth10n** [comment]
Same here for Mono 6.80.96 and Debian 9.9!
